
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Project } from '@/types/project';
import { ProjectDialog } from './ProjectDialog';
import { ProjectList } from './projects/ProjectList';
import { CategoryFilter } from './projects/CategoryFilter';

const projects: Project[] = [
  {
    id: 1,
    slideshow: [
      "/lovable-uploads/3fc501d4-453c-48bc-a4dc-47ccc1cda170.png",
      "/lovable-uploads/27556d3b-f65b-4216-a1f8-08448be0a811.png",
      "/lovable-uploads/582f1fc5-4d6e-461e-a7fc-1e7c84c65309.png"
    ],
    title: "The Old Cemetery",
    category: "VRChat Worlds",
    visits: "60,000+",
    description: <>🏆 Featured by VRChat for Spookality 2024 <br/><span className="font-bold text-[#0FA0CE]"><a href="https://x.com/search?q=%22The%20Old%20Cemetery%22%20Axinovium&src=typed_query" target="_blank" rel="noopener noreferrer" className="hover:underline">100k+ Impressions on X</a></span></>,
    link: "https://vrchat.com/home/launch?worldId=wrld_7482338d-40b9-4c8d-92fb-bc1623e7122f"
  },
  {
    id: 2,
    slideshow: [
      "/lovable-uploads/ee2ba1d7-900b-4495-8621-807c6c03310f.png",
      "/lovable-uploads/debfe5e2-da8f-4175-a8f5-5dcbb4a5c8cb.png",
      "/lovable-uploads/2a27a6d8-18b1-4d2a-b0b9-61c26b2264ce.png",
      "/lovable-uploads/5d81b536-e241-4f42-b786-9e325dec7fa5.png",
      "/lovable-uploads/ddaf6bbf-4c95-4d6a-b0f9-80363e46330d.png"
    ],
    title: "Warm With You",
    category: "VRChat Worlds",
    description: <>A cozy Christmas bedroom in the Swiss Alps<br/>🏆 <a href="https://www.meshy.ai/collections/Colorful-Furry-ChristmasAdventure-collection-by-Axinovium-0193ccb2-3938-738c-8195-1050793c29f5" className="text-purple-400 hover:text-purple-300 underline" target="_blank" rel="noopener noreferrer">Winner Meshy 2024 Christmas Adventure event</a></>,
    link: "https://vrchat.com/home/launch?worldId=wrld_741c199d-ee56-46b4-9488-e99150847974"
  },
  {
    id: 3,
    slideshow: [
      "/lovable-uploads/ebc49ac0-e46c-401c-8b0a-d49a5619172c.png",
      "/lovable-uploads/85f7aef3-6107-482b-be4f-e4dc90559920.png",
      "/lovable-uploads/c9b972bd-0fa4-4763-a0cf-3ed848552340.png",
      "/lovable-uploads/da08b244-37ce-4683-81c7-aa7621bdf289.png"
    ],
    title: "Opal Bay",
    category: "VRChat Worlds",
    visits: "130k",
    description: <span>A tropical beach with white sand and sparkling opal-like water <br/><span className="font-bold text-[#0FA0CE]"><a href="https://x.com/search?q=%22Opal%20Bay%22%20Axinovium&src=typed_query" target="_blank" rel="noopener noreferrer" className="hover:underline">200k+ Impressions on X</a></span></span>,
    link: "https://vrchat.com/home/launch?worldId=wrld_eca2ddde-f794-4c59-ae3a-4dd5881eb18b"
  },
  {
    id: 4,
    slideshow: [
      "/lovable-uploads/946741e4-08ba-4910-a127-6a40c8e086bf.png",
      "/lovable-uploads/afa862c3-b65c-4c43-aea1-085ff0a409c7.png",
      "/lovable-uploads/b338aed7-e9b7-41cd-87b6-7ee5562c3d14.png",
      "/lovable-uploads/4d599d75-cedc-4c1c-a0e3-765d43163e6a.png"
    ],
    title: "Meshy Fanhub",
    category: "VRChat Worlds",
    description: <>A commissioned world showcasing Meshy AI 3D Model Gen for VRChat Avatars and Worlds, with examples and tutorials.<br/><a href="https://www.youtube.com/watch?v=-V_93GThVdU" target="_blank" rel="noopener noreferrer" className="text-green-400 hover:text-green-300">Showcase video link</a></>,
    link: "https://vrchat.com/home/launch"
  },
  {
    id: 5,
    title: "Cloud Temple",
    category: "VRChat Worlds",
    description: "This world was an experiment building almost entirely with AI 3D Models generated by Meshy-3",
    videoId: "XNy-O5opCUc",
    link: "https://vrchat.com/home/launch?worldId=wrld_c690ffd0-a9b7-403a-9845-f3360584132a"
  },
  {
    id: 6,
    slideshow: [
      "/lovable-uploads/fdc9356e-651f-4874-83d8-817e14175a82.png",
      "/lovable-uploads/4a7224dd-00a3-4a66-bc0f-b7fb529ec728.png",
      "/lovable-uploads/08ea863f-65c6-4c61-9b22-0854b3baf55d.png"
    ],
    title: "High Orbit",
    category: "VRChat Worlds",
    description: <>A cozy bedroom on a satellite in high orbit․ Puzzle world requiring 4 people to finish.<br/>🏆Featured by VRChat for Space Jam 2024</>,
    link: "https://vrchat.com/home/launch?worldId=wrld_0bd6cc56-3e37-4530-a43c-8c7e6647bd1e"
  },
  // Content Creation projects
  {
    id: 7,
    title: "Meshy Fanhub VRChat World Showcase Commission",
    category: "Content Creation",
    description: "A video showcase of the Meshy Fanhub",
    videoId: "-V_93GThVdU",
    link: "https://www.youtube.com/watch?v=-V_93GThVdU"
  },
  {
    id: 8,
    title: "Meshy AI For VRChat Avatar Creation TUTORIAL",
    category: "Content Creation",
    description: "A full tutorial for how to turn Meshy characters into VRChat Avatars",
    videoId: "VoUWYyVmcoQ",
    link: "https://www.youtube.com/watch?v=VoUWYyVmcoQ"
  },
  {
    id: 9,
    title: "Meshy 2-year Anniversary showcase",
    category: "Content Creation",
    description: "A scene I created using community models submitted for the Meshy #AroundTheWorld# celebration event. Animated with AI.",
    videoId: "14Kcrj3iAH0",
    link: "https://www.youtube.com/watch?v=14Kcrj3iAH0"
  },
  // Adding the new video
  {
    id: 10,
    title: "Axinovium Worlds Showcase",
    category: "Content Creation",
    description: "VRchat virtual reality worlds I created between 2023-2025. Some unreleased.",
    videoId: "h13kD1Bga6M",
    link: "https://www.youtube.com/watch?v=h13kD1Bga6M"
  },
  // Adding new Community project
  {
    id: 11,
    title: "Meshy #AroundTheWorld# 2-Year Anniversary event",
    category: "Community",
    description: "Designed and managed this global event as Meshy's Community Ambassador, for 2.5 million users.",
    link: "#",
    slideshow: ["/lovable-uploads/84a09bb2-7dc3-44e9-9ef6-bbf3a1258b17.png"] // Using Venice award image as placeholder
  }
];

export const ProjectsGallery = () => {
  const [activeCategory, setActiveCategory] = useState("All");
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const categories = ["All", "VRChat Worlds", "Content Creation", "Community", "Free Tools"];

  const filteredProjects = activeCategory === "All" 
    ? projects 
    : projects.filter(project => project.category === activeCategory);

  const handleProjectSelect = (project: Project) => {
    if (project.videoId) {
      setSelectedProject(project);
    } else {
      window.open(project.link, '_blank');
    }
  };

  return (
    <section className="py-12 bg-black" id="our-projects">
      <div className="container mx-auto px-4">
        <motion.h2
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-7xl font-bold text-center mb-8 py-4 bg-gradient-to-r from-blue-400 via-purple-500 to-pink-400 text-transparent bg-clip-text leading-relaxed"
        >
          Our Projects
        </motion.h2>

        <CategoryFilter
          categories={categories}
          activeCategory={activeCategory}
          onSelectCategory={setActiveCategory}
        />
        
        <ProjectList
          projects={filteredProjects}
          onSelect={handleProjectSelect}
        />
      </div>

      <ProjectDialog
        project={selectedProject}
        onClose={() => setSelectedProject(null)}
      />
    </section>
  );
};
